# Generated by Django 5.0.1 on 2024-01-29 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laptop_id', models.IntegerField(unique=True)),
                ('model_name', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('ram', models.CharField(max_length=50)),
                ('processor', models.CharField(max_length=50)),
                ('price', models.FloatField()),
            ],
        ),
    ]
